cnp_settings:
  training_epochs: 1
  context_ratio: 0.333
  context_is_subset: True
  batch_size_train: 500
  files_per_batch_train: 20
  batch_size_predict: [1000]
  files_per_batch_predict: 1
  number_of_walkers: 1
  config_wise: False
  use_data_augmentation: "mixup" #"smote" #False #"mixup"
  use_beta: [0.1,0.1] # uniform => None, beta => [a,b] U-shape [0.1,0.1] Uniform [1.,1.] falling [0.2,0.5] rising [0.2,0.5]
  signal_to_background_ratio: "" # "_1to4" # used for smote augmentation
  ratio_testing_vs_training: 1/40
  plot_after: 200

feature_settings:
  feature_size: 30
  target_size: 1
  x_mean: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  x_std: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
          1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
          1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

simulation_settings:
  theta_headers: ["metallicity","envelope_eff_alpha","sigma_bh","sigma_ns"]
  theta_headers_plot: ["metallicity","$\\alpha_{CE}$","$\\sigma_{BH}$","$\\sigma_{NS}$"]
  phi_labels: ["CH_on_MS(1)","CH_on_MS(2)","Eccentricity@ZAMS","Equilibrated_At_Birth","Evolution_Status","Mass@ZAMS(1)","Mass@ZAMS(2)","Merger","Merger_At_Birth","Metallicity@ZAMS(1)","Metallicity@ZAMS(2)","Omega@ZAMS(1)","Omega@ZAMS(2)","PO_CE_Alpha","PO_LBV_Factor","PO_Sigma_Kick_CCSN_BH","PO_Sigma_Kick_CCSN_NS","PO_Sigma_Kick_ECSN","PO_Sigma_Kick_USSN","PO_WR_Factor","SN_Kick_Magnitude_Random_N","SemiMajorAxis@ZAMS","Stellar_Type(1)","Stellar_Type(2)","Stellar_Type@ZAMS(1)","Stellar_Type@ZAMS(2)"]
  #phi_all: ["CH_on_MS(1)","CH_on_MS(2)","Eccentricity@ZAMS","Equilibrated_At_Birth","Error","Evolution_Status","Mass@ZAMS(1)","Mass@ZAMS(2)","Merger","Merger_At_Birth","Metallicity@ZAMS(1)","Metallicity@ZAMS(2)","Omega@ZAMS(1)","Omega@ZAMS(2)","PO_CE_Alpha","PO_LBV_Factor","PO_Sigma_Kick_CCSN_BH","PO_Sigma_Kick_CCSN_NS","PO_Sigma_Kick_ECSN","PO_Sigma_Kick_USSN","PO_WR_Factor","Record_Type","SEED","SN_Kick_Magnitude_Random_N","SemiMajorAxis@ZAMS","Stellar_Type(1)","Stellar_Type(2)","Stellar_Type@ZAMS(1)","Stellar_Type@ZAMS(2)","Unbound"]
  target_headers: ["BBH Events"]
  target_headers_plot: "$\\hat{\\epsilon}$"
  target_range: [0,1]
  signal_condition: ["BBH Events==1"]
  # Set parameter boundaries
  theta_min: [0.0001,0,0,0]
  theta_max: [0.031,10,1000,1000]

  #reference_meanMassEvolved_efficiency = (1.57133427*1e-6)/0.005)
  #sfr = 1e7 # Msun Gpc^-3 (Madau andDickinson, 2014) 
  #merger_rate = sfr * efficiency_simulation *reference_meanMassEvolved_efficiency
  #print(merger_rate, 'mergers [year^-1 Gpc^-3]')
  observed_rate: 17 # with error bars 17+10, 17-6.7) # yr^-1 Gpc^-3 
  #print(observed_rate, 'observed mergers [year^-1 Gpc^-3]') 
  y_scaling: 3142.6685399999997
  lf_cost: 1
  hf_cost: 1000

mfgp_settings:
  noise:
    lf: !!float 0.021
  #  mf: !!float 0.0069 
    hf: !!float 0.0

pce_settings:
  polynomial_order: 4
  priors:
    lf:
      sigma_coeffs_prior_type: default
      sigma_coeffs: 0.1
      sigma_y: !!float 0.021  # Replace with your LF_cnp_noise value

    # mf:
    #   mu_rho: 1.
    #   sigma_rho: 0.1
    #   sigma_coeffs_prior_type: default
    #   sigma_coeffs_delta: 0.1
    #   sigma_y: !!float 0.0069 

    hf:
      mu_rho: !!float 0.49466
      sigma_rho: !!float 0.15313
      sigma_coeffs_prior_type: default
      sigma_coeffs_delta: 0.1
      sigma_y: !!float 0.006  #

path_settings:
  version: v1.2
  path_to_files_train: ../in/data/lf/v1.2/iteration_0
  path_to_files_predict: ["../in/data/lf/v1.2/iteration_0"]
  iteration: [0]
  fidelity: [0]
  path_to_files_validation: ../out/cnp/cnp_v1.2_output_validation.csv
  path_out_cnp:  ../out/cnp
  path_out_mfgp:  ../out/mfgp
  path_out_pce:  ../out/pce
